# Generated by Django 5.1.5 on 2026-09-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0041_repair_hollihop_schema_drift'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststage',
            name='mode',
            field=models.CharField(blank=True, default='full_test', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teststage',
            name='time_multiplier',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
